'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class user
    Public Property id As Integer
    Public Property product_name As String
    Public Property product_price As Integer
    Public Property edit_from As String
    Public Property created As Date
    Public Property modified As Date
    Public Property status As String

End Class
